site_name: Cosmos Cleaner Wiki
site_description: Clean up space junk, upgrade your ship, and become the best cleaner in the cosmos!
site_author: Derek Perry
site_url: 'https://wiki.cosmoscleaner.com'
copyright: "<p style='padding-bottom:10px;'><img src='../../static/logo/CosmosCleaner_Logotype_ColorOnDark-Padded.svg' alt='' width=300 height=300/></p>
<a href='https://CosmosCleaner.com' title='CosmosCleaner.com'><em>Go to Game Website</em></a> | <a href='https://CosmosCleaner.com/privacy' title='CosmosCleaner.com/privacy'><em>Privacy Policy</em></a> | <a href='https://CosmosCleaner.com/tos' title='CosmosCleaner.com/tos'><em>Terms of Service</em></a> | <a href='https://CosmosCleaner.com/copyright' title='CosmosCleaner.com/copyright'><em>Copyright/Licenses</em></a>
<p>Copyright © 2023 <a href='https://CosmosCleaner.com' title='CosmosCleaner.com'>Cosmos Cleaner</a>™</p><p>Game by <a href='https://derek-perry.com' title='Go to Derek Perry's website at derek-perry.com'>Derek Perry</a> <img src='../../static/dp.svg' alt='' width=16 height=16/></p>"
nav:
  - Go to Game Website: https://cosmoscleaner.com
  - Wiki:
    - index.md
  - Characters:
    - characters.md
    - CET: cet.md
    - Cosmo: cosmo.md
  - Clutter:
    - clutter.md
    - Aluminum: aluminum.md
    - Steel: steel.md
    - Copper: copper.md
    - Titanium: titanium.md
    - Silver: silver.md
    - Gold: gold.md
    - Lithium: lithium.md
    - Sapphire: sapphire.md
    - Emerald: emerald.md
    - Ruby: ruby.md
    - Diamond: diamond.md
    - Fuel: fuel.md
    - Random Box: box.md
  - Locations:
    - locations.md
    - HQ: hq.md
plugins:
    - search
    - section-index
    - git-revision-date
    - macros
    - enumerate-headings:
        increment_across_pages: false
        exclude:
          - index.md
          - characters.md
          - clutter.md
          - locations.md
extra:
  social:
    - icon: x
      link: https://x.com/CosmosCleaner
      name: X (formerly Twitter)
    - icon: instagram
      link: https://instagram.com/CosmosCleaner
      name: Instagram
    - icon: threads
      link: https://threads.net/@CosmosCleaner
      name: Threads
    - icon: facebook
      link: https://facebook.com/CosmosCleaner
      name: Facebook
    - icon: youtube
      link: https://youtube.com/@CosmosCleaner
      name: YouTube
    - icon: reddit
      link: https://reddit.com/r/CosmosCleaner
      name: Reddit
    - icon: discord
      link: https://discord.gg/sncuXN5n2q
      name: Discord
  manifest: static/favicon/site.webmanifest
  generator: false
theme:
  name: material
  language: en
  icon:
    logo: logo
  favicon: static/favicon/favicon.ico
  font:
    text: Bai Jamjuree
    code: Bai Jamjuree
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - content.tabs.link
  custom_dir: overrides
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: '#'
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css