site_name: Cosmos Cleaner Wiki
site_description: Clean up space junk, upgrade your ship, and become the best cleaner in the cosmos!
copyright: "<a href='https://CosmosCleaner.com' title='CosmosCleaner.com'><em>Go to main website 🔗</em></a><p>Cosmos Cleaner &copy; 2023 Game by <a href='https://derek-perry.com' title='Go to Derek Perry's website at derek-perry.com'>Derek Perry</a></p>"
nav:
  - Go to Main Website: https://cosmoscleaner.com
  - Wiki: index.md
  - Characters:
    - Characters: characters/index.md
    - CET: characters/cet.md
    - Cosmo: characters/cosmo.md
  - Clutter:
    - Clutter: clutter/index.md
    - Aluminum: clutter/aluminum.md
    - Steel: clutter/steel.md
    - Copper: clutter/copper.md
    - Titanium: clutter/titanium.md
    - Silver: clutter/silver.md
    - Gold: clutter/gold.md
    - Lithium: clutter/lithium.md
    - Sapphire: clutter/sapphire.md
    - Emerald: clutter/emerald.md
    - Ruby: clutter/ruby.md
    - Diamond: clutter/diamond.md
    - Random Box: clutter/box.md
plugins:
    - search
    - section-index
    - git-revision-date
    - macros
    - enumerate-headings:
        increment_across_pages: false
        exclude:
          - index.md
          - characters/index.md
          - clutter/index.md
extra:
  ccName: Cosmos Cleaner
  ccURL: cosmoscleaner.com
  characterTypes: "|Character||Type|
    \n|-|-|-|
    \n|[CET](/characters/cet/ 'CET (Player Character)')|[![CET](../static/characters/character-cet.png 'CET (Player Character)')](/characters/cet/)|Player|
    \n|[Cosmo](/characters/cosmo/ 'Cosmo (Narrator Character)')|[![Cosmo](../static/characters/character-cosmo.png 'Cosmo (Narrator Character)')](/characters/cosmo/)|Narrator|
  "
  clutterTypes: "|Clutter Type||Value|Mass|
    \n|-|-|-|-|
    \n|[Aluminum](/clutter/aluminum/ 'Aluminum (Metal Clutter)')|[![Aluminum](../static/clutter/clutter-aluminum.png 'Aluminum (Metal Clutter)')](/clutter/aluminum/)|$10|10g|
    \n|[Steel](/clutter/steel/ 'Steel (Metal Clutter)')|[![Steel](../static/clutter/clutter-steel.png 'Steel (Metal Clutter)')](/clutter/steel/)|$30|15g|
    \n|[Copper](/clutter/copper/ 'Copper (Metal Clutter)')|[![Copper](../static/clutter/clutter-copper.png 'Copper (Metal Clutter)')](/clutter/copper/)|$60|30g|
    \n|[Titanium](/clutter/titanium/ 'Titanium (Metal Clutter)')|[![Titanium](../static/clutter/clutter-titanium.png 'Titanium (Metal Clutter)')](/clutter/titanium/)|$100|50g|
    \n|[Silver](/clutter/silver/ 'Silver (Metal Clutter)')|[![Silver](../static/clutter/clutter-silver.png 'Silver (Metal Clutter)')](/clutter/silver/)|$250|70g|
    \n|[Gold](/clutter/gold/ 'Gold (Metal Clutter)')|[![Gold](../static/clutter/clutter-gold.png 'Gold (Metal Clutter)')](/clutter/gold/)|$750|100g|
    \n|[Lithium](/clutter/lithium/ 'Lithium (Metal Clutter)')|[![Lithium](../static/clutter/clutter-lithium.png 'Lithium (Metal Clutter)')](/clutter/lithium/)|$2,000|80g|
    \n|[Sapphire](/clutter/sapphire/ 'Sapphire (Gem Clutter)')|[![Sapphire](../static/clutter/clutter-sapphire.png 'Sapphire (Gem Clutter)')](/clutter/sapphire/)|$5,000|10g|
    \n|[Emerald](/clutter/emerald/ 'Emerald (Gem Clutter)')|[![Emerald](../static/clutter/clutter-emerald.png 'Emerald (Gem Clutter)')](/clutter/emerald/)|$20,000|10g|
    \n|[Ruby](/clutter/ruby/ 'Ruby (Gem Clutter)')|[![Ruby](../static/clutter/clutter-ruby.png 'Ruby (Gem Clutter)')](/clutter/ruby/)|$50,000|10g|
    \n|[Diamond](/clutter/diamond/ 'Diamond (Gem Clutter)')|[![Diamond](../static/clutter/clutter-diamond.png 'Diamond (Gem Clutter)')](/clutter/diamond/)|$100,000|10g|
    \n|[Random Box](/clutter/box/ 'Random Box (Special Clutter)')|[![Random Box](../static/clutter/clutter-box.png 'Random Box (Special Clutter)')](/clutter/box/)|$?|?g|
  "
  social:
    - icon: x
      link: https://x.com/CosmosCleaner
      name: X (formerly Twitter)
    - icon: instagram
      link: https://instagram.com/CosmosCleaner
      name: Instagram
    - icon: threads
      link: https://threads.net/@CosmosCleaner
      name: Threads
    - icon: facebook
      link: https://facebook.com/CosmosCleaner
      name: Facebook
    - icon: youtube
      link: https://youtube.com/@CosmosCleaner
      name: YouTube
    - icon: reddit
      link: https://reddit.com/r/CosmosCleaner
      name: Reddit
    - icon: discord
      link: https://discord.gg/sncuXN5n2q
      name: Discord
  manifest: static/favicon/site.webmanifest
  generator: false
theme:
  name: material
  icon:
    logo: logo
  favicon: static/favicon/favicon.ico
  font:
    text: Bai Jamjuree
    code: Bai Jamjuree
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - toc:
      permalink: 🔗
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css